# Store version number in separate file so is easy to find and easy to track changes
# n.b. Deliberately capitalised so doesn't clash with app_VERSION var generated by
#      project(hoffgui VERSION ${APP_VERSION}) command

set(APP_VERSION 0.1.0)
